//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Consulta_Id {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="Consulta_Id.ZWS_CONSULTA_ID")]
    public interface ZWS_CONSULTA_ID {
        
        // CODEGEN: Generating message contract since the operation ZfiRfcManId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse1 ZfiRfcManId(SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse1> ZfiRfcManIdAsync(SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiRfcManId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoField;
        
        private string rindeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Rinde {
            get {
                return this.rindeField;
            }
            set {
                this.rindeField = value;
                this.RaisePropertyChanged("Rinde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfiRfcManIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechadocField;
        
        private System.DateTime fechaingField;
        
        private string idField;
        
        private decimal importelocalField;
        
        private decimal importerendidoField;
        
        private string mensajeField;
        
        private string monedaField;
        
        private string nombreField;
        
        private string referenciaField;
        
        private string resultadoField;
        
        private string rindioField;
        
        private decimal tipocambioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime Fechadoc {
            get {
                return this.fechadocField;
            }
            set {
                this.fechadocField = value;
                this.RaisePropertyChanged("Fechadoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime Fechaing {
            get {
                return this.fechaingField;
            }
            set {
                this.fechaingField = value;
                this.RaisePropertyChanged("Fechaing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Importelocal {
            get {
                return this.importelocalField;
            }
            set {
                this.importelocalField = value;
                this.RaisePropertyChanged("Importelocal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Importerendido {
            get {
                return this.importerendidoField;
            }
            set {
                this.importerendidoField = value;
                this.RaisePropertyChanged("Importerendido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("Moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("Referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Rindio {
            get {
                return this.rindioField;
            }
            set {
                this.rindioField = value;
                this.RaisePropertyChanged("Rindio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Tipocambio {
            get {
                return this.tipocambioField;
            }
            set {
                this.tipocambioField = value;
                this.RaisePropertyChanged("Tipocambio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiRfcManIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SAPConnectorLibrary.Consulta_Id.ZfiRfcManId ZfiRfcManId;
        
        public ZfiRfcManIdRequest() {
        }
        
        public ZfiRfcManIdRequest(SAPConnectorLibrary.Consulta_Id.ZfiRfcManId ZfiRfcManId) {
            this.ZfiRfcManId = ZfiRfcManId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfiRfcManIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse ZfiRfcManIdResponse;
        
        public ZfiRfcManIdResponse1() {
        }
        
        public ZfiRfcManIdResponse1(SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse ZfiRfcManIdResponse) {
            this.ZfiRfcManIdResponse = ZfiRfcManIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_CONSULTA_IDChannel : SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_CONSULTA_IDClient : System.ServiceModel.ClientBase<SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID>, SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID {
        
        public ZWS_CONSULTA_IDClient() {
        }
        
        public ZWS_CONSULTA_IDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_CONSULTA_IDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_CONSULTA_IDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_CONSULTA_IDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse1 SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID.ZfiRfcManId(SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest request) {
            return base.Channel.ZfiRfcManId(request);
        }
        
        public SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse ZfiRfcManId(SAPConnectorLibrary.Consulta_Id.ZfiRfcManId ZfiRfcManId1) {
            SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest inValue = new SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest();
            inValue.ZfiRfcManId = ZfiRfcManId1;
            SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse1 retVal = ((SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID)(this)).ZfiRfcManId(inValue);
            return retVal.ZfiRfcManIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse1> SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID.ZfiRfcManIdAsync(SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest request) {
            return base.Channel.ZfiRfcManIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdResponse1> ZfiRfcManIdAsync(SAPConnectorLibrary.Consulta_Id.ZfiRfcManId ZfiRfcManId) {
            SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest inValue = new SAPConnectorLibrary.Consulta_Id.ZfiRfcManIdRequest();
            inValue.ZfiRfcManId = ZfiRfcManId;
            return ((SAPConnectorLibrary.Consulta_Id.ZWS_CONSULTA_ID)(this)).ZfiRfcManIdAsync(inValue);
        }
    }
}
