//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstradaSAPConnectorContainer : DbContext
    {
        public EstradaSAPConnectorContainer()
            : base("name=EstradaSAPConnectorContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAPC_Rendicion> SAPC_Rendicion { get; set; }
        public virtual DbSet<SAPC_FacturaProveedor> SAPC_FacturaProveedor { get; set; }
        public virtual DbSet<SAPC_FondoFijo> SAPC_FondoFijo { get; set; }
        public virtual DbSet<SAPC_Session> SAPC_Session { get; set; }
        public virtual DbSet<SAPC_SAPRPCCall> SAPC_SAPRPCCall { get; set; }
        public virtual DbSet<SAPC_EndPoint> SAPC_EndPoint { get; set; }
        public virtual DbSet<SAPC_Adelantos> SAPC_Adelantos { get; set; }
        public virtual DbSet<SAPC_Estados> SAPC_Estados { get; set; }
        public virtual DbSet<SAPC_Proveedores> SAPC_Proveedores { get; set; }
        public virtual DbSet<SAPC_Empleado> SAPC_Empleado { get; set; }
        public virtual DbSet<SAPC_CECO> SAPC_CECO { get; set; }
        public virtual DbSet<SAPC_InputacionesFacturas> SAPC_InputacionesFacturas { get; set; }
        public virtual DbSet<SAPC_Sociedades> SAPC_Sociedades { get; set; }
        public virtual DbSet<SAPC_ClaseDoc> SAPC_ClaseDoc { get; set; }
        public virtual DbSet<SAPC_Monedas> SAPC_Monedas { get; set; }
        public virtual DbSet<SAPC_Paises> SAPC_Paises { get; set; }
        public virtual DbSet<SAPC_Results> SAPC_Results { get; set; }
        public virtual DbSet<SAPC_Poblaciones> SAPC_Poblaciones { get; set; }
        public virtual DbSet<SAPC_Comprobante> SAPC_Comprobante { get; set; }
        public virtual DbSet<SAPC_InputacionesComprobantes> SAPC_InputacionesComprobantes { get; set; }
        public virtual DbSet<InnovActionWFAccionEstado> InnovActionWFAccionEstadoes { get; set; }
        public virtual DbSet<InnovActionWFAnticipoDeGasto> InnovActionWFAnticipoDeGastos { get; set; }
        public virtual DbSet<InnovActionWFAntiRendRelationship> InnovActionWFAntiRendRelationships { get; set; }
        public virtual DbSet<InnovActionWFAprobadore> InnovActionWFAprobadores { get; set; }
        public virtual DbSet<InnovActionWFCaso> InnovActionWFCasos { get; set; }
        public virtual DbSet<InnovActionWFCCAprobadore> InnovActionWFCCAprobadores { get; set; }
        public virtual DbSet<InnovActionWFEmailAccount> InnovActionWFEmailAccounts { get; set; }
        public virtual DbSet<InnovActionWFEstadoRolOwner> InnovActionWFEstadoRolOwners { get; set; }
        public virtual DbSet<InnovActionWFFile> InnovActionWFFiles { get; set; }
        public virtual DbSet<InnovActionWFInst> InnovActionWFInsts { get; set; }
        public virtual DbSet<InnovActionWFInstHist> InnovActionWFInstHists { get; set; }
        public virtual DbSet<InnovActionWFLicVariasExa> InnovActionWFLicVariasExas { get; set; }
        public virtual DbSet<InnovActionWFLicVariasFall> InnovActionWFLicVariasFalls { get; set; }
        public virtual DbSet<InnovActionWFLicVariasMat> InnovActionWFLicVariasMats { get; set; }
        public virtual DbSet<InnovActionWFLicVariasMud> InnovActionWFLicVariasMuds { get; set; }
        public virtual DbSet<InnovActionWFLicVariasNac> InnovActionWFLicVariasNacs { get; set; }
        public virtual DbSet<InnovActionWFLicVariasOtro> InnovActionWFLicVariasOtros { get; set; }
        public virtual DbSet<InnovActionWFLicVariasTipo> InnovActionWFLicVariasTipoes { get; set; }
        public virtual DbSet<InnovActionWFPageDomain> InnovActionWFPageDomains { get; set; }
        public virtual DbSet<InnovActionWFPedidoVacacione> InnovActionWFPedidoVacaciones { get; set; }
        public virtual DbSet<InnovActionWFReintegroDeGasto> InnovActionWFReintegroDeGastos { get; set; }
        public virtual DbSet<InnovActionWFRendicionDeGasto> InnovActionWFRendicionDeGastos { get; set; }
        public virtual DbSet<InnovActionWFRoleAprobador> InnovActionWFRoleAprobadors { get; set; }
        public virtual DbSet<InnovActionWFState> InnovActionWFStates { get; set; }
        public virtual DbSet<InnovActionWFStockDia> InnovActionWFStockDias { get; set; }
        public virtual DbSet<InnovActionWFVariable> InnovActionWFVariables { get; set; }
        public virtual DbSet<SAPC_AnticipoGastos> SAPC_AnticipoGastos { get; set; }
        public virtual DbSet<SAPC_Aprobadores> SAPC_Aprobadores { get; set; }
        public virtual DbSet<SAPC_BotonesWFTipos> SAPC_BotonesWFTipos { get; set; }
        public virtual DbSet<SAPC_CeCo_UserID> SAPC_CeCo_UserID { get; set; }
        public virtual DbSet<SAPC_CuentasContables> SAPC_CuentasContables { get; set; }
        public virtual DbSet<SAPC_EmailTemplates> SAPC_EmailTemplates { get; set; }
        public virtual DbSet<SAPC_Facturas> SAPC_Facturas { get; set; }
        public virtual DbSet<SAPC_HistFacturas> SAPC_HistFacturas { get; set; }
        public virtual DbSet<SAPC_JefeAprobadores> SAPC_JefeAprobadores { get; set; }
        public virtual DbSet<SAPC_Rechazos> SAPC_Rechazos { get; set; }
        public virtual DbSet<SAPC_ReintegroGastos> SAPC_ReintegroGastos { get; set; }
        public virtual DbSet<SAPC_RendicionFF> SAPC_RendicionFF { get; set; }
        public virtual DbSet<SAPC_RendicionG> SAPC_RendicionG { get; set; }
        public virtual DbSet<SAPC_RendicionGastosSAPC_SAPRPCCall1> SAPC_RendicionGastosSAPC_SAPRPCCall1 { get; set; }
        public virtual DbSet<SAPC_TipoFacturas> SAPC_TipoFacturas { get; set; }
        public virtual DbSet<SAPC_BotonesWF> SAPC_BotonesWF { get; set; }
        public virtual DbSet<SAPC_OtrosComprobantes> SAPC_OtrosComprobantes { get; set; }
    }
}
