//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstradaSAPConnectorContainer : DbContext
    {
        public EstradaSAPConnectorContainer()
            : base("name=EstradaSAPConnectorContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAPC_RendicionABC> SAPC_RendicionABC { get; set; }
        public virtual DbSet<SAPC_FacturaProveedor> SAPC_FacturaProveedor { get; set; }
        public virtual DbSet<SAPC_FondoFijo> SAPC_FondoFijo { get; set; }
        public virtual DbSet<SAPC_Session> SAPC_Session { get; set; }
        public virtual DbSet<SAPC_SAPRPCCall> SAPC_SAPRPCCall { get; set; }
        public virtual DbSet<SAPC_EndPoint> SAPC_EndPoint { get; set; }
        public virtual DbSet<SAPC_Adelantos> SAPC_Adelantos { get; set; }
        public virtual DbSet<SAPC_Estados> SAPC_Estados { get; set; }
        public virtual DbSet<SAPC_Proveedores> SAPC_Proveedores { get; set; }
        public virtual DbSet<SAPC_Empleado> SAPC_Empleado { get; set; }
        public virtual DbSet<SAPC_CECO> SAPC_CECO { get; set; }
        public virtual DbSet<SAPC_Inputaciones> SAPC_Inputaciones { get; set; }
        public virtual DbSet<SAPC_Sociedades> SAPC_Sociedades { get; set; }
        public virtual DbSet<SAPC_ClaseDoc> SAPC_ClaseDoc { get; set; }
        public virtual DbSet<SAPC_Monedas> SAPC_Monedas { get; set; }
        public virtual DbSet<SAPC_Paises> SAPC_Paises { get; set; }
        public virtual DbSet<SAPC_Results> SAPC_Results { get; set; }
        public virtual DbSet<SAPC_Poblaciones> SAPC_Poblaciones { get; set; }
    }
}
