
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InnovActionWFAntiRendRelationship
{

    public int IDRelationship { get; set; }

    public int InstanceIDAnti { get; set; }

    public int InstanceIDRend { get; set; }

}

}
