//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnovActionWFInst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InnovActionWFInst()
        {
            this.InnovActionWFInstHists = new HashSet<InnovActionWFInstHist>();
            this.InnovActionWFVariables = new HashSet<InnovActionWFVariable>();
        }
    
        public int InstanceID { get; set; }
        public int CasoID { get; set; }
        public int UserIDOwner { get; set; }
        public int StateCode { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> InstGUID { get; set; }
    
        public virtual InnovActionWFCaso InnovActionWFCaso { get; set; }
        public virtual InnovActionWFInst InnovActionWFInst1 { get; set; }
        public virtual InnovActionWFInst InnovActionWFInst2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnovActionWFInstHist> InnovActionWFInstHists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnovActionWFVariable> InnovActionWFVariables { get; set; }
    }
}
