
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InnovActionWFCaso
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InnovActionWFCaso()
    {

        this.InnovActionWFAccionEstadoes = new HashSet<InnovActionWFAccionEstado>();

        this.InnovActionWFInsts = new HashSet<InnovActionWFInst>();

        this.InnovActionWFRoleAprobadors = new HashSet<InnovActionWFRoleAprobador>();

        this.SAPC_BotonesWF = new HashSet<SAPC_BotonesWF>();

    }


    public int CasoID { get; set; }

    public string Caso { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InnovActionWFAccionEstado> InnovActionWFAccionEstadoes { get; set; }

    public virtual InnovActionWFCaso InnovActionWFCasos1 { get; set; }

    public virtual InnovActionWFCaso InnovActionWFCaso1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InnovActionWFInst> InnovActionWFInsts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InnovActionWFRoleAprobador> InnovActionWFRoleAprobadors { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SAPC_BotonesWF> SAPC_BotonesWF { get; set; }

}

}
