//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnovActionWFInstHist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InnovActionWFInstHist()
        {
            this.InnovActionWFVariables = new HashSet<InnovActionWFVariable>();
        }
    
        public int HistoryID { get; set; }
        public int InstanceID { get; set; }
        public int UserIDSignedBy { get; set; }
        public Nullable<int> UserIDNextSigner { get; set; }
        public Nullable<int> RoleIDNextSigner { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int StateID { get; set; }
        public System.DateTime Create_tstamp { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Remindersent { get; set; }
        public string Systemurl { get; set; }
        public Nullable<System.Guid> FolderGUID { get; set; }
        public Nullable<System.Guid> HistGuid { get; set; }
    
        public virtual InnovActionWFInst InnovActionWFInst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnovActionWFVariable> InnovActionWFVariables { get; set; }
    }
}
