
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InnovActionWFAccionEstado
{

    public int AccionEstado_ID { get; set; }

    public string Accion { get; set; }

    public int StateCode { get; set; }

    public string StoreProcedure { get; set; }

    public int CasoID { get; set; }

    public bool EstadoInicial { get; set; }



    public virtual InnovActionWFCaso InnovActionWFCaso { get; set; }

}

}
