//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPC_Comprobantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAPC_Comprobantes()
        {
            this.Inputaciones = new HashSet<SAPC_InputacionesComprobantes>();
            this.RPCCalls = new HashSet<SAPC_SAPRPCCall>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaCont { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public string Referencia { get; set; }
        public string Tienda { get; set; }
        public string SAPNroDoc { get; set; }
        public string DocComp1 { get; set; }
        public string DocComp2 { get; set; }
        public string DocComp3 { get; set; }
        public string DocComp4 { get; set; }
        public string DocComp5 { get; set; }
        public string DocComp6 { get; set; }
        public string DocComp7 { get; set; }
        public string DocComp8 { get; set; }
        public string DocComp9 { get; set; }
        public string DocComp10 { get; set; }
        public string DocComp11 { get; set; }
    
        public virtual SAPC_ClaseDoc ClaseDoc { get; set; }
        public virtual SAPC_Sociedades Sociedad { get; set; }
        public virtual SAPC_Monedas Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_InputacionesComprobantes> Inputaciones { get; set; }
        public virtual SAPC_FondoFijo FondoFijo { get; set; }
        public virtual SAPC_Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_SAPRPCCall> RPCCalls { get; set; }
        public virtual SAPC_Estados Estado { get; set; }
    }
}
