//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPC_RendicionGastosSAPC_SAPRPCCall1
    {
        public int RendicionesGastos_Id { get; set; }
        public int SAPRPCCall_Id { get; set; }
    
        public virtual SAPC_SAPRPCCall SAPC_SAPRPCCall { get; set; }
    }
}
