//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPC_Rendicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAPC_Rendicion()
        {
            this.RPCCalls = new HashSet<SAPC_SAPRPCCall>();
            this.FacturasProveedor = new HashSet<SAPC_FacturaProveedor>();
            this.OtrosComprobantes = new HashSet<SAPC_OtrosComprobantes>();
            this.Adelantos = new HashSet<SAPC_Adelantos>();
        }
    
        public int Id { get; set; }
        public string SAPNroDoc { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Error { get; set; }
    
        public virtual SAPC_FondoFijo FondoFijo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_SAPRPCCall> RPCCalls { get; set; }
        public virtual SAPC_Estados Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_FacturaProveedor> FacturasProveedor { get; set; }
        public virtual SAPC_Empleado RendidoPor { get; set; }
        public virtual SAPC_Comprobante Comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_OtrosComprobantes> OtrosComprobantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_Adelantos> Adelantos { get; set; }
    }
}
