//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPC_FacturaProveedor
    {
        public int Id { get; set; }
        public string TipoDocumento { get; set; }
        public decimal ImporteNeto { get; set; }
        public decimal Fecha { get; set; }
        public short PtoVenta { get; set; }
        public decimal NumeroDocumento { get; set; }
        public decimal BaseIVA21 { get; set; }
        public decimal BaseIVA105 { get; set; }
        public decimal BaseIVA27 { get; set; }
        public decimal BaseIVA0 { get; set; }
        public string ImporteTotalAPagar { get; set; }
        public string Percepcion1Importe { get; set; }
        public string Percepcion2Importe { get; set; }
    
        public virtual SAPC_RendicionABC RendicionGastos { get; set; }
        public virtual SAPC_Proveedor Proveedor { get; set; }
        public virtual SAPC_CECO CECO { get; set; }
        public virtual SAPC_Percepciones Percepcion1 { get; set; }
        public virtual SAPC_Percepciones Percepcion2 { get; set; }
        public virtual SAPC_Empleado RendidoPor { get; set; }
    }
}
