
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SAPC_RendicionFF
{

    public int RendicionID { get; set; }

    public Nullable<int> InstanceID { get; set; }

    public int UserID { get; set; }

    public int FondoFijoID { get; set; }

    public string Descripcion { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaAdelanto { get; set; }

    public Nullable<decimal> Adelanto { get; set; }

    public Nullable<decimal> Saldo { get; set; }

    public Nullable<int> FirmaJefe { get; set; }

    public Nullable<int> FirmaAdministracion { get; set; }

    public Nullable<int> FirmaContabilidad { get; set; }

    public string RendicionGUID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> ModificadoPor { get; set; }

    public System.DateTime FechaModificacion { get; set; }

    public Nullable<int> RechazoID { get; set; }

    public string RechazoTexto { get; set; }

    public Nullable<int> RechazadoPor { get; set; }



    public virtual SAPC_FondoFijo SAPC_FondoFijo { get; set; }

    public virtual SAPC_Rechazos SAPC_Rechazos { get; set; }

}

}
