
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SAPC_CeCo_UserID
{

    public int UsernameCeCoID { get; set; }

    public int UserID { get; set; }

    public int CeCoID { get; set; }



    public virtual SAPC_CeCo_UserID SAPC_CeCo_UserID1 { get; set; }

    public virtual SAPC_CeCo_UserID SAPC_CeCo_UserID2 { get; set; }

}

}
