
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SAPC_Session
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SAPC_Session()
    {

        this.RPCCalls = new HashSet<SAPC_SAPRPCCall>();

    }


    public int Id { get; set; }

    public System.DateTime Comienzo { get; set; }

    public System.DateTime Final { get; set; }

    public string ErrorMessage { get; set; }

    public string ErrorCode { get; set; }



    public virtual SAPC_EndPoint EndPoint { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SAPC_SAPRPCCall> RPCCalls { get; set; }

}

}
