//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPC_Comprobante
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
    
        public virtual SAPC_RendicionComp RendicionComp { get; set; }
        public virtual SAPC_Proveedor Proveedor { get; set; }
        public virtual SAPC_CECO CECO { get; set; }
    }
}
