
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SAPC_Aprobadores
{

    public int AprobadorID { get; set; }

    public int UserID { get; set; }

    public Nullable<int> Jefe { get; set; }

    public Nullable<int> SegundaAprob { get; set; }

    public Nullable<int> TerceraAprobCentral { get; set; }

    public Nullable<int> IFContabilidad { get; set; }

    public Nullable<int> TerceraAprobAdmin { get; set; }

    public Nullable<int> IFAdministracion { get; set; }

}

}
