//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPC_FondoFijo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAPC_FondoFijo()
        {
            this.RendicionesGastos = new HashSet<SAPC_Rendicion>();
            this.Adelantos = new HashSet<SAPC_Adelantos>();
            this.SAPC_RendicionFF = new HashSet<SAPC_RendicionFF>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> CreadoEn { get; set; }
        public string SAPId { get; set; }
        public Nullable<int> Credentials_Id { get; set; }
        public Nullable<int> UserIDTitular { get; set; }
        public Nullable<int> UserIDSuplente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_Rendicion> RendicionesGastos { get; set; }
        public virtual SAPC_Estados Estado { get; set; }
        public virtual SAPC_EndPoint EndPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_Adelantos> Adelantos { get; set; }
        public virtual SAPC_Credentials SAPC_Credentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPC_RendicionFF> SAPC_RendicionFF { get; set; }
    }
}
