
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SAPC_Rechazos
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SAPC_Rechazos()
    {

        this.SAPC_AnticipoGastos = new HashSet<SAPC_AnticipoGastos>();

        this.SAPC_ReintegroGastos = new HashSet<SAPC_ReintegroGastos>();

        this.SAPC_RendicionG = new HashSet<SAPC_RendicionG>();

        this.SAPC_RendicionFF = new HashSet<SAPC_RendicionFF>();

    }


    public int RechazoID { get; set; }

    public string Descripcion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SAPC_AnticipoGastos> SAPC_AnticipoGastos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SAPC_ReintegroGastos> SAPC_ReintegroGastos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SAPC_RendicionG> SAPC_RendicionG { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SAPC_RendicionFF> SAPC_RendicionFF { get; set; }

}

}
