
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SAPConnectorLibrary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SAPC_BotonesWF
{

    public int BotonID { get; set; }

    public int CasoID { get; set; }

    public string Color { get; set; }

    public string Accion { get; set; }

    public string Texto { get; set; }

    public string FontAwesome { get; set; }

    public string Estilo { get; set; }

    public Nullable<int> TipoBotonID { get; set; }



    public virtual InnovActionWFCaso InnovActionWFCaso { get; set; }

    public virtual SAPC_BotonesWFTipos SAPC_BotonesWFTipos { get; set; }

}

}
