//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConnectorLibrary.Solicitud_Anticipo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO")]
    public interface ZWS_SOLICITUD_ANTICIPO {
        
        // CODEGEN: Generating message contract since the operation ZFI_RFC_SOLICITUD_ANTICIPO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SOLICITUD_ANTICIPO:ZFI_RFC_SOLICITUD_A" +
            "NTICIPORequest", ReplyAction="urn:sap-com:document:sap:rfc:functions:ZWS_SOLICITUD_ANTICIPO:ZFI_RFC_SOLICITUD_A" +
            "NTICIPOResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse1 ZFI_RFC_SOLICITUD_ANTICIPO(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_SOLICITUD_ANTICIPO:ZFI_RFC_SOLICITUD_A" +
            "NTICIPORequest", ReplyAction="urn:sap-com:document:sap:rfc:functions:ZWS_SOLICITUD_ANTICIPO:ZFI_RFC_SOLICITUD_A" +
            "NTICIPOResponse")]
        System.Threading.Tasks.Task<SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse1> ZFI_RFC_SOLICITUD_ANTICIPOAsync(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFI_RFC_SOLICITUD_ANTICIPO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZFI_RFC_ANTICIPOS[] t_DETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public ZFI_RFC_ANTICIPOS[] T_DETALLE {
            get {
                return this.t_DETALLEField;
            }
            set {
                this.t_DETALLEField = value;
                this.RaisePropertyChanged("T_DETALLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFI_RFC_ANTICIPOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fECHA_DOCField;
        
        private string cLASE_DOCField;
        
        private string sOCIEDADField;
        
        private string mONEDAField;
        
        private string rEFERENCIAField;
        
        private string tIENDAField;
        
        private string tEXTO_CABField;
        
        private string cTA_CONTABLE1Field;
        
        private string iND_CMEField;
        
        private decimal iMPORTEField;
        
        private System.DateTime fECHA_VTOField;
        
        private string tEXTO_POSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime FECHA_DOC {
            get {
                return this.fECHA_DOCField;
            }
            set {
                this.fECHA_DOCField = value;
                this.RaisePropertyChanged("FECHA_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CLASE_DOC {
            get {
                return this.cLASE_DOCField;
            }
            set {
                this.cLASE_DOCField = value;
                this.RaisePropertyChanged("CLASE_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SOCIEDAD {
            get {
                return this.sOCIEDADField;
            }
            set {
                this.sOCIEDADField = value;
                this.RaisePropertyChanged("SOCIEDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string REFERENCIA {
            get {
                return this.rEFERENCIAField;
            }
            set {
                this.rEFERENCIAField = value;
                this.RaisePropertyChanged("REFERENCIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TIENDA {
            get {
                return this.tIENDAField;
            }
            set {
                this.tIENDAField = value;
                this.RaisePropertyChanged("TIENDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TEXTO_CAB {
            get {
                return this.tEXTO_CABField;
            }
            set {
                this.tEXTO_CABField = value;
                this.RaisePropertyChanged("TEXTO_CAB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CTA_CONTABLE1 {
            get {
                return this.cTA_CONTABLE1Field;
            }
            set {
                this.cTA_CONTABLE1Field = value;
                this.RaisePropertyChanged("CTA_CONTABLE1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IND_CME {
            get {
                return this.iND_CMEField;
            }
            set {
                this.iND_CMEField = value;
                this.RaisePropertyChanged("IND_CME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
                this.RaisePropertyChanged("IMPORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime FECHA_VTO {
            get {
                return this.fECHA_VTOField;
            }
            set {
                this.fECHA_VTOField = value;
                this.RaisePropertyChanged("FECHA_VTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TEXTO_POS {
            get {
                return this.tEXTO_POSField;
            }
            set {
                this.tEXTO_POSField = value;
                this.RaisePropertyChanged("TEXTO_POS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFI_RFC_SOLICITUD_ANTICIPOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mENSAJEField;
        
        private string nRO_DOCField;
        
        private string rESULTADOField;
        
        private ZFI_RFC_ANTICIPOS[] t_DETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NRO_DOC {
            get {
                return this.nRO_DOCField;
            }
            set {
                this.nRO_DOCField = value;
                this.RaisePropertyChanged("NRO_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public ZFI_RFC_ANTICIPOS[] T_DETALLE {
            get {
                return this.t_DETALLEField;
            }
            set {
                this.t_DETALLEField = value;
                this.RaisePropertyChanged("T_DETALLE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFI_RFC_SOLICITUD_ANTICIPORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPO ZFI_RFC_SOLICITUD_ANTICIPO;
        
        public ZFI_RFC_SOLICITUD_ANTICIPORequest() {
        }
        
        public ZFI_RFC_SOLICITUD_ANTICIPORequest(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPO ZFI_RFC_SOLICITUD_ANTICIPO) {
            this.ZFI_RFC_SOLICITUD_ANTICIPO = ZFI_RFC_SOLICITUD_ANTICIPO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFI_RFC_SOLICITUD_ANTICIPOResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse ZFI_RFC_SOLICITUD_ANTICIPOResponse;
        
        public ZFI_RFC_SOLICITUD_ANTICIPOResponse1() {
        }
        
        public ZFI_RFC_SOLICITUD_ANTICIPOResponse1(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse ZFI_RFC_SOLICITUD_ANTICIPOResponse) {
            this.ZFI_RFC_SOLICITUD_ANTICIPOResponse = ZFI_RFC_SOLICITUD_ANTICIPOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_SOLICITUD_ANTICIPOChannel : SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_SOLICITUD_ANTICIPOClient : System.ServiceModel.ClientBase<SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO>, SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO {
        
        public ZWS_SOLICITUD_ANTICIPOClient() {
        }
        
        public ZWS_SOLICITUD_ANTICIPOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_SOLICITUD_ANTICIPOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SOLICITUD_ANTICIPOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_SOLICITUD_ANTICIPOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse1 SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO.ZFI_RFC_SOLICITUD_ANTICIPO(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest request) {
            return base.Channel.ZFI_RFC_SOLICITUD_ANTICIPO(request);
        }
        
        public SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse ZFI_RFC_SOLICITUD_ANTICIPO(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPO ZFI_RFC_SOLICITUD_ANTICIPO1) {
            SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest inValue = new SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest();
            inValue.ZFI_RFC_SOLICITUD_ANTICIPO = ZFI_RFC_SOLICITUD_ANTICIPO1;
            SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse1 retVal = ((SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO)(this)).ZFI_RFC_SOLICITUD_ANTICIPO(inValue);
            return retVal.ZFI_RFC_SOLICITUD_ANTICIPOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse1> SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO.ZFI_RFC_SOLICITUD_ANTICIPOAsync(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest request) {
            return base.Channel.ZFI_RFC_SOLICITUD_ANTICIPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPOResponse1> ZFI_RFC_SOLICITUD_ANTICIPOAsync(SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPO ZFI_RFC_SOLICITUD_ANTICIPO) {
            SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest inValue = new SAPConnectorLibrary.Solicitud_Anticipo.ZFI_RFC_SOLICITUD_ANTICIPORequest();
            inValue.ZFI_RFC_SOLICITUD_ANTICIPO = ZFI_RFC_SOLICITUD_ANTICIPO;
            return ((SAPConnectorLibrary.Solicitud_Anticipo.ZWS_SOLICITUD_ANTICIPO)(this)).ZFI_RFC_SOLICITUD_ANTICIPOAsync(inValue);
        }
    }
}
